### ISSUE TITLE
An error  is thrown while running the COCO code

### ISSUE THREAD

**Issue by JetWings** [ShenghaiRong/BECO#7]
Set 'coco_set' to True. An error message is thrown ,

  2%|█▍                                                       | 1/40 [1:06:53<42:39:46, 3938.13s/it]
Val_metrics: Overall_Acc:nan, mClass_Acc:nan, mPred_Acc:nan, mIoU:nan, Best:None, 18:48:54 epoch_runner INFO Time taken for validating : 1.25 mins
Traceback (most recent call last):
  File "/home/BECO-main/main.py", line 381, in <module>
    main()
  File "/home/BECO-main/main.py", line 102, in main
    main_worker(None, args)
  File "/home/BECO-main/main.py", line 349, in main_worker
    runner.run()
  File "/home/BECO-main/runners/epoch_runner.py", line 102, in run
    self._end_workflow(mode)
  File "/home/BECO-main/runners/epoch_runner.py", line 139, in _end_workflow
    self._hook_dict['TBLoggerHook'].log_val(self)
  File "/home/BECO-main/hooks/logger/tensorboard.py", line 60, in log_val
    self.writer.add_scalars(self.tag_table['val'], metrics_dict, step)
  File "/home/miniconda3/envs/py/lib/python3.8/site-packages/torch/utils/tensorboard/writer.py", line 403, in add_scalars
    fw.add_summary(scalar(main_tag, scalar_value),
  File "/home/miniconda3/envs/py/lib/python3.8/site-packages/torch/utils/tensorboard/summary.py", line 249, in scalar
    scalar = make_np(scalar)
  File "/home/miniconda3/envs/py/lib/python3.8/site-packages/torch/utils/tensorboard/_convert_np.py", line 24, in make_np
    raise NotImplementedError(
NotImplementedError: Got <class 'NoneType'>, but numpy array, torch tensor, or caffe2 blob name are expected.

**Comment by ShenghaiRong** [comment]
The error has been fixed, please refer to the following:
https://github.com/ShenghaiRong/BECO/blob/6a57bed601a940cd2337d1465589418648a3a035/hooks/logger/tensorboard.py#L60
And I recommend setting the "del_ckpt" configuration in hooks/\_\_init\_\_.py to "False" when training BECO on the COCO dataset, which might help with the offline evaluation of checkpoints of every epoch.

**Comment by JetWings** [comment]
Thanks!

**Comment by JetWings** [comment]
The validation results during the training phase are all nan.

**Comment by ShenghaiRong** [comment]
Please refer to:
https://github.com/ShenghaiRong/BECO/issues/4#issuecomment-1607033152
